#!/bin/sh

VMMALLOC_LIB=/usr/local/lib64/libvmmalloc.so.1

echo VMMALLOC_POOL_DIR=$1 VMMALLOC_POOL_SIZE=$2 LD_PRELOAD=$VMMALLOC_LIB $3 >> $4
VMMALLOC_POOL_DIR=$1 VMMALLOC_POOL_SIZE=$2 LD_PRELOAD=$VMMALLOC_LIB $3 >> $4 2>&1

